name: Deploy to Production

permissions:
  contents: read

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Clean up existing containers
        run: docker compose down --rmi all --volumes --remove-orphans

      - name: Build and deploy
        run: docker compose up -d --build
